all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      cumulus_new_password: "<CUMULUS_NEW_PASSWORD>1!"
      netris_admin_password: "<NETRIS_ADMIN_PASSWORD>1!"
      redfish_password: "<REDFISH_PASSWORD>"
      ctl_public_ip: "<CTL_PUBLIC_IP>"
      netris_license: "<NETRIS_LICENSE>"


      # Artifacts
      netris_operator_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/netris-operator
      netris_operator_chart_version: 0.0.1-d71fc01
      netris_operator_image: registry.ci.mirantis.com/k0rdent-bm/images/netris-operator
      netris_operator_image_tag: 0.0.1-d71fc01.1770641523

      ufo_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/unified-fabric-operator
      ufo_chart_version: 0.0.1-8586bfe
      ufo_image_tag: 0.0.1-8586bfe.1769198335
