---
- name: Install Netris Controller
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  ignore_errors: false
  vars:
    workspace: /opt/ufo_lab/
    netris_charts_repo: https://github.com/jumpojoy/netris-charts
    netris_charts_branch: extensions
    netris_chars_dir: "{{ workspace }}/netris-charts"

  tasks:
    - name: Ensure target directory
      file:
        path:  "{{ workspace }}"
        state: directory

    - name: Download charts repo
      ansible.builtin.git:
        repo: "{{ netris_charts_repo }}"
        dest: "{{ netris_chars_dir }}"
        version: "{{ netris_charts_branch }}"

    - name: Make chart dependencies
      ansible.builtin.shell:
        cmd: |
          helm dep up
          rm -rf .cache
        chdir: "{{ netris_chars_dir }}/charts/netris-controller/"

    - name: Ensure target directory
      file:
        path: "{{ k8s_artifacts_dir }}/netris/"
        state: directory

    - name: Handle templates
      block:
        - name: Render templates
          ansible.builtin.template:
            src: "k8s/netris/{{ item }}"
            dest: "{{ k8s_artifacts_dir }}/netris/{{ item }}"
          with_items:
           - "netris_controller.yaml"

    - name: Deploy/upgrade netris controller helm release
      kubernetes.core.helm:
        name: netris-controller
        kubeconfig: "{{ kubeconfig_path }}"
        chart_ref: "{{ netris_chars_dir }}/charts/netris-controller/"
        release_namespace: netris-controller
        create_namespace: true
        values_files:
          - "{{ k8s_artifacts_dir }}/netris/netris_controller.yaml"
        state: present
        wait: true
        wait_timeout: 300s
