controller:
  host: "{{ netris_web_api_url }}"
  login: "{{ netris_admin_username }}"
  password: "{{ netris_admin_password }}"
image:
  repository: "{{ netris_operator_image }}"
  tag: "{{ netris_operator_image_tag }}"
